In [4]:
import numpy as np

A = np.array([[0, 1],
              [1, 2],
              [2, 3]])

# A^T * A
A_T_A = A.T @ A

A_dagger = np.linalg.inv(A_T_A) @ A.T
P_R_A = A @ A_dagger
A_T_A_inv = np.linalg.inv(A_T_A)

print("Transpose:", A.T)
print("Matrix A^T * A is:\n", A_T_A)
print("Inverse of A^T * A is:\n", A_T_A_inv)
print("Generalized inverse A^dagger is:\n", A_dagger)
print("Projection P_R(A) is:\n", P_R_A)

Transpose: [[0 1 2]
 [1 2 3]]
Matrix A^T * A is:
 [[ 5  8]
 [ 8 14]]
Inverse of A^T * A is:
 [[ 2.33333333 -1.33333333]
 [-1.33333333  0.83333333]]
Generalized inverse A^dagger is:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 0.83333333  0.33333333 -0.16666667]]
Projection P_R(A) is:
 [[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
